runtime: java11
instance_class: F2
env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored

env_variables:
  SPRING_PROFILES_ACTIVE: production
  # Add any other environment variables your application needs here

automatic_scaling:
  target_cpu_utilization: 0.65

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

network:
  session_affinity: true